### ISSUE TITLE
rats-tls: how to support trusted communication between SGX node and CSV node

### ISSUE THREAD

**Issue by haosanzi** [inclavare-containers/inclavare-containers#1351]
**Background:**
`rats-tls` need to support [Secure and trusted communication of heterogeneous HW-TEE nodes](https://github.com/alibaba/inclavare-containers/blob/master/rats-tls/docs/design/design.md#secure-and-trusted-communication-of-heterogeneous-hw-tee-nodes).   

![image](https://user-images.githubusercontent.com/26923638/131601334-a4338295-2c3c-4111-9087-38b22f311898.png)

As shown in above picture:
Step 1: `enclave-tls-server` running in SGX node will generate ecdsa cert and verify CSV cert.
Step2: `enclave-tls-client` running in CSV node will generate csv cert and verify SGX ecdsa cert.

**Problem:**
Right now, I have added CSV verifier `libverifier_csv.so` and attester `libattester_csv.so`. 
The problem is how can `enclave-tls-server` running in SGX node verify CSV cert with `libverifier_csv.so` while generating SGX cert?  Since all codes are running enclave in SGX enclave, how can `enclave-tls-server` running in enclave registers csv verifier and calls csv verifier to verify  CSV cert?

**Comment by haosanzi** [comment]
It may be necessary to put the csv verifier related code in the enclave. Since csv verifier relies on SM2, rats-tls need to be adapted to babassl first.

**Comment by jiazhang0** [comment]
Some comments.

- In theory, CSV node and SGX node can serve both client and server.
- In SGX build mode, all verifier instances have to be implemented in enclave.

**Comment by uudiin** [comment]
A simpler way, you can consider porting the patchset of making OpenSSL in enclave to BabaSSL.

**Comment by jiazhang0** [comment]
According to the discussion, there are 3 options:
- OPT 1：cherry pick the necessary SM2/3 source code chunks to openssl used by rats-tls
- OPT 2：call openssl/babassl high level APIs for SM2/3
- OPT 3：implement enclavazation for babassl

**Comment by jiazhang0** [comment]
Blocked by https://github.com/alibaba/inclavare-containers/issues/1349.
