### ISSUE TITLE
TAG-Runtime: Presentation Discussion

### ISSUE THREAD

**Issue by raravena80** [inclavare-containers/inclavare-containers#1421]
I'm one of the co-chairs of the CNCF TAG-Runtime, I'm reaching out and think it would be great for you to present/discuss the project at one of our meetings. An overview of the project would be great.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by jiazhang0** [comment]
@raravena80 We are pleased to present this project on TAG-Runtime. We plan to attend on this meeting after National Day holiday after Oct 10. I will reach out to you once the schedule is confirmed.

**Comment by raravena80** [comment]
@jiazhang0 thanks let us kniw!

**Comment by raravena80** [comment]
@jiazhang0 following up here. Would Dec 16th 8am PT work to present in our [meeting](https://bit.ly/cncf-tag-runtime-meeting-notes)? Thanks!

**Comment by jiazhang0** [comment]
@raravena80 No problem. It is suitable for us now.
