### ISSUE TITLE
build mode: if we still need keep "tdx" as a separate build mode in future? 

### ISSUE THREAD

**Issue by zhiminghufighting** [inclavare-containers/inclavare-containers#1544]

**Comment by zhiminghufighting** [comment]
Depends on if sgx and tdx sdk will be combined in future at end of 2022/Q1.

**Comment by jiazhang0** [comment]
The only meaningful build modes are host, occlum and sgx, because they correspond to different programming model. TDX mode (and incoming SEV/CSV mode) is just a sub-build mode within host mode for manually selection.
