### ISSUE TITLE
rats-tls: warning: Missing build-id in /root/rpmbuild/BUILDROOT for build rats-tls rpm package in the centos 8.2

### ISSUE THREAD

**Issue by haosanzi** [inclavare-containers/inclavare-containers#823]
```
warning: Missing build-id in /root/rpmbuild/BUILDROOT/enclave-tls-0.6.1-1.el8.x86_64/opt/enclave-tls/lib/libenclave_tls.so.0.1.0
warning: Missing build-id in /root/rpmbuild/BUILDROOT/enclave-tls-0.6.1-1.el8.x86_64/opt/enclave-tls/lib/tls-wrappers/libtls_wrapper_nulltls.so
warning: Missing build-id in /root/rpmbuild/BUILDROOT/enclave-tls-0.6.1-1.el8.x86_64/opt/enclave-tls/lib/tls-wrappers/libtls_wrapper_wolfssl.so
```

**Comment by hustliyilin** [comment]
From the [rpm-software-management/rpm issue](https://github.com/rpm-software-management/rpm/issues/367), we can get two conclusions:

- This is not experienced in rpm version 4.13.0.2 and only  experienced with the latest rpm version 4.14.0.
- Occlum also has the same issue([Missing Build-ID when building RPM packages for 0.21.0](https://github.com/occlum/occlum/issues/358) ), and currently occlum use a `%global _missing_build_ids_terminate_build 0` flag as a workaround. But more investigation is preferred.

**Comment by hustliyilin** [comment]
`%global _missing_build_ids_terminate_build 0 ` isn't right for `enclave-tls`, we need to generate the debuginfo package for `enclave-tls`, so we use `%undefine _missing_build_ids_terminate_build` flag as a workaround. So I think this issue is not important and we can refer to occlum's solution later.

**Comment by hustliyilin** [comment]
So I change the label `bug` and `medium` to `low` and `workaround`.

**Comment by jiazhang0** [comment]
Adding --build-id in LDFLAGS is not enough?

**Comment by hustliyilin** [comment]
> Adding --build-id to LDFLAGS cannot resolve this problem?

Maybe set `-Wl,--build-id=none` in Makefile is a good option.

**Comment by hustliyilin** [comment]
When I add `-Wl, --build-id={md5, sha1, none}` according to [this guide](http://sourceware.org/binutils/docs-2.23.1/ld/Options.html#Options), like the following codes, this warning still remains, so through add LDFLAGS `-Wl, --build-id={md5, sha1, none}` can't solve this problem @jiazhang0 

```Makefile
   ldflags += -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lm
 else ifdef OCCLUM
diff --git a/enclave-tls/samples/enclave-tls-server/Makefile b/enclave-tls/samples/enclave-tls-server/Makefile
index f0cf0c8..5f34e37 100644
--- a/enclave-tls/samples/enclave-tls-server/Makefile
+++ b/enclave-tls/samples/enclave-tls-server/Makefile
@@ -11,7 +11,8 @@ Targets := $(Build_Bindir)/enclave-tls-server
 cflags := $(CFLAGS) -I$(Topdir)/src/include
 ldflags := \
   $(LDFLAGS) -L$(Topdir)/build/lib -lenclave_tls \
-  -Wl,--rpath=/opt/enclave-tls/lib,--enable-new-dtags
+  -Wl,--rpath=/opt/enclave-tls/lib,--enable-new-dtags \
+  -Wl,--build-id=md5
 ifdef SGX
   ldflags += -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lm
 else ifdef OCCLUM
```

**Comment by jiazhang0** [comment]
Should add --build-id= to LDFLAGS defined in build_env.mk

**Comment by hustliyilin** [comment]
Do you mean that in addition to the above three files, I also need to add `-Wl,--build-id` into `build_env.mk` ?

**Comment by jiazhang0** [comment]
> > Should add --build-id= to LDFLAGS defined in build_env.mk
> 
> Do you mean that in addition to the above three files, I also need to add `-Wl,--build-id` into `build_env.mk` ?

Yes. See the warning log. The affected components are instances and core library whose ldflags is controlled by LDFLAGS defined in build_env.mk. The modifications to other places don't make sense.

**Comment by hustliyilin** [comment]
> > > Should add --build-id= to LDFLAGS defined in build_env.mk
> > 
> > 
> > Do you mean that in addition to the above three files, I also need to add `-Wl,--build-id` into `build_env.mk` ?
> 
> Yes. See the warning log. The affected components are instances and core library whose ldflags is controlled by LDFLAGS defined in build_env.mk. The modifications to other places don't make sense.

Ok，I'll retry it

**Comment by hustliyilin** [comment]
It is not a good option add `--build-id` in the   `rules/build_env.mk`

1. when I set `-Wl,--build-id=none` in the `rules/build_env.mk`, there are an error like this:

![image](https://user-images.githubusercontent.com/6824093/119075762-f01d3600-ba23-11eb-877d-b2893491d1c2.png)

2. when I set `--build-id=none` in the `rules/build_env.mk`, there are an error like this:

![image](https://user-images.githubusercontent.com/6824093/119075856-19d65d00-ba24-11eb-928a-a390b970869b.png)

**Comment by jiazhang0** [comment]
@hustliyilin This is caused by LDFLAGS which is used in different way. ld should use --build-id and cc shoud use -Wl,-build-id.

**Comment by hustliyilin** [comment]
> @hustliyilin This is caused by LDFLAGS which is used in different way. ld should use --build-id and cc shoud use -Wl,-build-id.

ok
